-- Clears existing job data and converts jobs.id (and the job_files.job_id
-- foreign key that references it) from a BIGINT identity to a UUID.
DROP TABLE IF EXISTS job_files;
DROP TABLE IF EXISTS jobs;

CREATE TABLE jobs (
                      id UUID PRIMARY KEY,
                      status VARCHAR(32) NOT NULL,
                      source_filename VARCHAR(255) NOT NULL,
                      page_count INTEGER,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      CONSTRAINT chk_jobs_status CHECK (status IN ('QUEUED', 'PROCESSING', 'DONE', 'FAILED'))
);

CREATE TABLE job_files (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           job_id UUID NOT NULL,
                           output_path VARCHAR(255) NOT NULL,
                           size BIGINT NOT NULL,
                           CONSTRAINT uq_job_files_job_id UNIQUE (job_id),
                           CONSTRAINT fk_job_files_job_id FOREIGN KEY (job_id) REFERENCES jobs (id) ON DELETE CASCADE
);