CREATE TABLE job_metrics (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             job_id UUID NOT NULL,
                             source_word_count INTEGER,
                             output_word_count INTEGER,

                             CONSTRAINT uq_job_metrics_job_id UNIQUE (job_id),

                             CONSTRAINT fk_job_metrics_job_id
                                 FOREIGN KEY (job_id)
                                     REFERENCES jobs (id)
                                     ON DELETE CASCADE
);