spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true

spring.jpa.hibernate.ddl-auto=validate

# PDF upload configuration (configure max size file when we finally agree on it)
app.upload.directory=uploads
app.upload.max-size=10MB 

# Multipart limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB