spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

app.upload.directory=${APP_UPLOAD_DIRECTORY:uploads}
app.upload.max-size-bytes=${APP_UPLOAD_MAX_SIZE_BYTES:10485760}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
