spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.flyway.enabled=true
spring.jpa.hibernate.ddl-auto=validate

app.upload.directory=${APP_UPLOAD_DIRECTORY:uploads}
app.upload.max-size-bytes=${APP_UPLOAD_MAX_SIZE_BYTES:15728640}

app.cleanup.retention=${APP_CLEANUP_RETENTION:PT30M}
app.cleanup.cron=${APP_CLEANUP_CRON:0 */10 * * * *}

spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
